TaskAssignment/Areas/Admin/Controllers/AttendanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskAssignment.Persistence;
using TaskAssignment.Areas.Admin.Models;
using TaskAssignment.Util;

namespace TaskAssignment.Areas.Admin.Controllers
{
    public class AttendanceController : Controller
    {
        // GET: Admin/Attendance
        public ActionResult Index() {
            return View();
        }

        public JsonResult AbsentList(DateTime id) {
            return null;
        }


        public ActionResult Absent(DateTime? id) {
            // id refers to the objective month
            if (!id.HasValue) {
                return View();
            }
            else {
                int month = id.Value.Month;
                var ctx = new TaskAssignmentModel();
                var model = ctx.Attendances.Where(att => att.AttendanceType.IsAbsent && att.StartDate.Month == month);
                ViewBag.Date = id.Value.ToString("yyyy-MM");
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Export(DateTime id) {
            string template = Server.MapPath("~/Content/templates/template-attendance.xlsx");
            string exported = Server.MapPath("~/Content/exported/" + "考勤记录-" + id.ToString("yyyy-MM-dd") + ".xlsx");
            var ctx = new TaskAssignmentModel();
            var members = ctx.Members.Where(m => m.IsInternal && m.Enable);
            var record = ctx.Attendances.Where(att => att.StartDate.Month == id.Month && 
                                                      att.StartDate.Year == id.Year && 
                                                      att.Member.Enable);
            var absType = ctx.AttendanceTypes.Where(t => t.IsAbsent);
            var t_holidays = ctx.Holidays.SingleOrDefault(h => h.Year == id.Year);
            var thd = t_holidays.Holidays.Split(';').Where(h => h.StartsWith(id.ToString("MM") + "-")).ToArray();
            var tex = t_holidays.ExtraWorkdays.Split(';').Where(e => e.StartsWith(id.ToString("MM") + "-")).ToArray();

            int[] holidays = new int[thd.Count()];
            int[] extraWorkdays = new int[tex.Count()];
            for (int i = 0; i < holidays.Length; i++) {
                holidays[i] = Convert.ToInt32(thd[i].Substring(3));
            }
            for (int i = 0; i < extraWorkdays.Length; i++) {
                extraWorkdays[i] = Convert.ToInt32(tex[i].Substring(3));
            }

            try {
                Global.Logger.AppendLog("Export");
                ExcelHelper.Export(id, members, record, absType, holidays, extraWorkdays, template, exported);
            }
            catch (Exception ex) {
                Global.Logger.AppendLog(ex);
            }
            //GC.Collect();

            FilePathResult r;
            if (System.IO.File.Exists(exported)) {
                r = new FilePathResult(exported, ExcelHelper.XlsxContentType);
                r.FileDownloadName = "考勤记录-" + id.ToString("yyyy-MM-dd") + ".xlsx";
                return r;
            }
            else {
                Global.Logger.AppendLog("Error occured!");
                return RedirectToAction("Error");
            }
        }

        [ChildActionOnly]
        public ActionResult TypeList(string id) {
            var ctx = new TaskAssignmentModel();
            IQueryable<AttendanceType> model = null;
            if (id != "absent") {
                model = ctx.AttendanceTypes.DefaultIfEmpty();
            }
            else {
                model = ctx.AttendanceTypes.Where(type => type.IsAbsent);
            }

            return View("_TypeList", model);
        }

        [HttpGet]
        public JsonResult Edit(long id) {
            var ctx = new TaskAssignmentModel();
            var absence = ctx.Attendances.SingleOrDefault(att => att.Id == id);
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            result.ContentEncoding = System.Text.Encoding.UTF8;
            // start, finish date, name, typename, comment
            result.Data = new {
                Id = absence.Id,
                StartDate = absence.StartDate.ToString("yyyy-MM-dd"),
                FinishDate = absence.FinishDate.ToString("yyyy-MM-dd"),
                MemberId = absence.MemberId,
                TypeId = absence.TypeId,
                Comments = absence.Comments
            };
            return result;
        }

        [HttpPost]
        public ActionResult Edit(AddAbsence model) {
            var ctx = new TaskAssignmentModel();
            var item = ctx.Attendances.SingleOrDefault(abs => abs.Id == model.Attendance.Id);
            item.MemberId = model.Attendance.MemberId;
            item.StartDate = model.Attendance.StartDate;
            item.FinishDate = model.Attendance.FinishDate;
            item.TypeId = model.Attendance.TypeId;
            item.Comments = model.Attendance.Comments;

            ctx.SaveChanges();

            string[] url = model.ReturnAction.Split('?');
            return RedirectToAction(url[0], new { id = url[1].Split('=')[1] });

        }

        public ActionResult Add(AddAbsence model) {
            var ctx = new TaskAssignmentModel();
            ctx.Attendances.Add(model.Attendance);
            ctx.SaveChanges();
            string[] url;
            if (!string.IsNullOrEmpty(model.ReturnAction)) {
                url = model.ReturnAction.Split('?');
                string act = url[0];
                string query = "";
                if (url.Length > 1) {
                    query = url[1].Split('=')[1];
                }
                return RedirectToAction(act, new { id = query });
            }
            else {
                return RedirectToAction("Absent");
            }

        }

        public ActionResult Delete(long id) {
            var ctx = new TaskAssignmentModel();
            var item = ctx.Attendances.SingleOrDefault(att => att.Id == id);
            ctx.Attendances.Remove(item);
            ctx.SaveChanges();
            return RedirectToAction("Absent");
        }

        public JsonResult Details(string id) {

            int month = DateTime.Parse(id).Month;
            var ctx = new TaskAssignmentModel();
            var model = ctx.Attendances.Where(att => att.StartDate.Month == month);
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            result.ContentEncoding = System.Text.Encoding.UTF8;

            if (model != null && model.Count() > 0) {
                List<object> data = new List<object>();
                foreach (var item in model) {
                    data.Add(new {
                        MemberId = item.MemberId,
                        TypeId = item.TypeId,
                        Alias = item.AttendanceType.Alias,
                        Symbol = item.AttendanceType.Symbol,
                        Start = item.StartDate.ToString("yyyy-MM-dd"),
                        Finish = item.FinishDate.ToString("yyyy-MM-dd")
                    });
                }
                result.Data = data;
                return result;
            }
            else {
                return null;
            }
        }
    }
}

TaskAssignment/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskAssignment.Persistence;

namespace TaskAssignment.Controllers
{
    public class MemberController : Controller
    {
        // GET: Member
        [ChildActionOnly]
        public ActionResult AllList()
        {
            var ctx = new TaskAssignmentModel();
            var model = ctx.Members.DefaultIfEmpty();
            return View("_AllList",model);
        }
    }
}

TaskAssignment/Areas/Admin/Views/Attendance/Absent.cshtml
@model IEnumerable<TaskAssignment.Persistence.Attendance>
@{
	ViewBag.Title = "休假 & 培训";
	ViewBag.AppendixStyle = Styles.Render("~/plugins/css/addTasks");
	ViewBag.AppendixScripts = Scripts.Render("~/plugins/js/addTasks");
	ViewBag.PartialView = "Absent_Script";
}
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">休假 & 培训查询</h3>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<div class="row">
					@using (Html.BeginForm("Absent", "Attendance", FormMethod.Get))
					{
						<div class="form-group col-md-3">
							<div class="input-group input-daterange">
								<div class="input-group-addon">
									<i class="fa fa-calendar"></i>
								</div>
								<input id="dpkr_month" class="form-control" data-val="true" name="id" type="text" value="@ViewBag.Date" />
								<div class="input-group-btn">
									<button type="submit" class="btn btn-success">查询</button>
								</div>
							</div>
						</div>
					}

				</div>

			</div>
			<table id="tb_absent" class="table table-bordered table-hover" width="100%">
				<thead>
					<tr>
						<th>时间</th>
						<th>姓名</th>
						<th>说明</th>
						<th>类型</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
					@{ if (Model != null)
					 {
						 foreach (var item in Model)
						 {
							<tr>
								<td>@item.StartDate.ToString("MM月dd日")~@item.FinishDate.ToString("MM月dd日")</td>
								<td>@item.Member.Name</td>
								<td>@item.Comments</td>
								<td>@item.AttendanceType.TypeName</td>
								<td>
									<div class="tools">
										<button id="btn_edit_@item.Id" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#editModal">
											<i class="fa fa-edit"></i>&nbsp;编&nbsp;辑&nbsp;
										</button>
										<button id="btn_del_@item.Id" class="btn btn-danger btn-xs pull-right" data-toggle="modal" data-target="#delModal">
											<i class="fa fa-trash-o"></i>&nbsp;删&nbsp;除&nbsp;
										</button>
									</div>
								</td>
							</tr>
						 }
					 }
					}
				</tbody>
			</table>
		</div>
		<!-- /.box-body -->
	</div>
	<!-- /.box -->
</div>
<div class="row">
	<div class="col-md-6">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">新增休假 & 培训记录</h3>
			</div>
			<div class="box-body">
				@using (Html.BeginForm("Add", "Attendance"))
				{
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label>时间：</label>
								<div class="input-group input-daterange">
									<div class="input-group-addon">
										<i class="fa fa-calendar"></i>
									</div>
									<input type="text" name="ReturnAction" value="Absent/@ViewBag.Date" style="display:none" />
									<input id="dpkr_start" class="form-control" data-val="true" name="Attendance.StartDate" type="text" value="@ViewBag.Start" />
									<div class="input-group-addon" style="border:none">至</div>
									<input id="dpkr_finish" name="Attendance.FinishDate" data-val="true" type="text" class="form-control" value="@ViewBag.Finish" />
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label>姓名：</label>
								<div class="input-group">
									<div class="input-group-addon">
										<i class="fa fa-user"></i>
									</div>
									<select name="Attendance.MemberId" class="form-control select2" style="width: 100%;">
										@Html.Action("AllList", "Member")
									</select>
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label>类型：</label>
								<div class="input-group">
									<div class="input-group-addon">
										<i class="fa fa-user"></i>
									</div>
									<select name="Attendance.TypeId" class="form-control select2" style="width: 100%;">
										@Html.Action("TypeList", "Attendance", new { id = "absent" })
									</select>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label>说明：</label>
								<textarea name="Attendance.Comments" class="form-control" rows="8" placeholder="输入说明或备注 ..."></textarea>
							</div>
						</div>
					</div>
					<div class="box-footer">
						<button type="submit" class="btn btn-primary pull-right">确&nbsp;&nbsp;认</button>
					</div>
				}

			</div>
		</div>
	</div>
</div>
@Html.Partial("EditModal")
@Html.Partial("DelModal")

TaskAssignment/Areas/Admin/Views/Attendance/Absent_Script.cshtml
<script>
	$(function () {
		$('.select2').select2();
		$('#tb_absent').DataTable({
			"columnDefs": [
                { "width": "12%", "targets": 0 },
				{ "width": "15%", "targets": 1 },
				{ "width": "15%", "targets": 4 }
			],
			'autoWidth': true,
			'lengthChange': false,
			'ordering': false,
			'info': false
		});

        $("#dpkr_month").datepicker({
            autoclose: true,
            todayHighlight: true,
            format: "yyyy-mm",

            minViewMode: "months",
            language: "zh-CN"
        });

		// for add absence datepicker
        $("#dpkr_start").datepicker({
        	autoclose: true,
        	todayHighlight: true,
        	language: "zh-CN"
        });

        $("#dpkr_finish").datepicker({
        	autoclose: true,
        	todayHighlight: true,
        	language: "zh-CN"
        });

		// for modal datepicker
        $("#dpkr_mstart").datepicker({
        	autoclose: true,
        	todayHighlight: true,
			language:"zh-CN"
        });

        $("#dpkr_mfinish").datepicker({
        	autoclose: true,
        	todayHighlight: true,
        	language: "zh-CN"
        });

        var delModal = $("#delModal");
        delModal.on("show.bs.modal", function (e) {
        	// 这里的btn就是触发元素，即你点击的删除按钮
        	var btn = $(e.relatedTarget),
                id = btn.attr("id").split('_')[2];
        	$("#delModal button[type='submit']").bind("click", function () {
        		location.href = location.protocol + "//" + location.host + "/Admin/Attendance/Delete/" + id + "?rtnact=Show";
        	});
        	// do your work
        })

        var editModal = $("#editModal");
        editModal.on("show.bs.modal", function (e) {
        	// 这里的btn就是触发元素，即你点击的删除按钮
        	var btn = $(e.relatedTarget),
                id = btn.attr("id").split('_')[2];
        	// do your work
        	$.getJSON(
                location.protocol + "//" + location.host + "/Admin/Attendance/Edit/" + id,
                function (data) {
                	$("#editModal input[name='Attendance.Id']").val(data.Id);
                	$("#editModal input[name='ReturnAction']").val("Absent?Id=" + "@ViewBag.Date");
                	$("#editModal input[name='Attendance.StartDate']").datepicker("setDate", data.StartDate);
                
                	$("#editModal input[name='Attendance.FinishDate']").datepicker("setDate", data.FinishDate);

                	$("#editModal textarea").html(data.Comments);

                	$("#editModal select[name='Attendance.TypeId']").val(data.TypeId);
                	$("#editModal select[name='Attendance.TypeId']").trigger("change");
                	$("#editModal select[name='Attendance.MemberId']").val(data.MemberId);
                	$("#editModal select[name='Attendance.MemberId']").trigger("change");
                });
        })



    });
</script>

TaskAssignment/Areas/Admin/Views/Attendance/DelModal.cshtml
<!-- Modal -->
<div class="modal modal-danger fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="取消"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">删除休假 & 培训记录</h4>
            </div>
            <div class="modal-body">
                确认删除该记录吗？（该操作不可逆）
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="submit" class="btn btn-danger" onclick="">删除</button>
            </div>
        </div>
    </div>
</div>

TaskAssignment/Areas/Admin/Views/Attendance/EditModal.cshtml
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="取消"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">修改休假 & 培训记录</h4>
            </div>
            @using (Html.BeginForm("Edit", "Attendance")) {
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>时间：</label>
								<div class="input-group input-daterange">
									<div class="input-group-addon">
										<i class="fa fa-calendar"></i>
									</div>
									<input type="text" name="Attendance.Id" style="display:none" />
									<input type="text" name="ReturnAction" style="display:none" />
									<input id="dpkr_mstart" class="form-control" data-val="true" name="Attendance.StartDate" type="text" value="@ViewBag.Start" />
									<div class="input-group-addon" style="border:none">至</div>
									<input id="dpkr_mfinish" name="Attendance.FinishDate" data-val="true" type="text" class="form-control" value="@ViewBag.Finish" />
								</div>
                            </div>
                        </div>     
                    </div>              
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>姓名：</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-user"></i>
                                    </div>
									<select name="Attendance.MemberId" class="form-control select2" style="width: 100%;">
										@Html.Action("AllList", "Member")
									</select>
                                </div>
                            </div>
                        </div>
						<div class="col-md-6">
							<div class="form-group">
								<label>类型：</label>
								<div class="input-group">
									<div class="input-group-addon">
										<i class="fa fa-user"></i>
									</div>
									<select name="Attendance.TypeId" class="form-control select2" style="width: 100%;">
										@Html.Action("TypeList", "Attendance", new { id = "absent" })
									</select>
								</div>
							</div>
						</div>      
                    </div>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label>说明：</label>
								<textarea name="Attendance.Comments" class="form-control" rows="8" placeholder="输入说明或备注 ..."></textarea>
							</div>
						</div>
					</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
            }
        </div>
    </div>
</div>

TaskAssignment/Areas/Admin/Views/Attendance/Index.cshtml
@model IEnumerable<TaskAssignment.Persistence.Task>
@{
    ViewBag.Title = "月度考勤";
    ViewBag.AppendixStyle = Styles.Render("~/plugins/css/addTasks");
    ViewBag.AppendixScripts = Scripts.Render("~/plugins/js/addTasks");
    ViewBag.PartialView = "Index_Script";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">月度考勤</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    @using (Html.BeginForm("Export", "Attendance")) {
                        <div class="form-group col-md-3">
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input id="dpkr_month" class="form-control" data-val="true" name="id" type="text" />
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-success" id="btn_query">查询</button>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-2 form-group pull-right">
                            <div class="input-group">
                                <button type="submit" id="btn_export" class="btn btn-danger"><i class="fa fa-download"></i>&nbsp;&nbsp;导出 Excel</button>
                            </div>
                        </div>
                    }

                </div>

            </div>
            <table id="tb_tasks" class="table table-bordered table-hover" width="100%">
                <thead>
                    <tr>
                        <th>日期</th>
                        @for (int i = 1; i <= 31; i++) {
                            <th>@i</th>
                        }
                        <th>出勤合计</th>
                        <th colspan="14" align="center">缺勤合计</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>姓名</td>
                        <td colspan="31"></td>
                        <td></td>
                        <td>迟到</td>
                        <td>事假</td>
                        <td>病假</td>
                        <td>补休</td>
                        <td>年休</td>
                        <td>婚丧</td>
                        <td>旷工</td>
                        <td>产假</td>
                        <td>护理假</td>
                        <td>工伤</td>
                        <td>探亲</td>
                        <td>培训</td>
                        <td>出差</td>
                        <td>其他</td>
                    </tr>
                    @Html.Action("AttendanceMemberList", "Member")
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>

TaskAssignment/Areas/Admin/Views/Attendance/Index_Script.cshtml
<script>
    function isWeekday(day) {
        if (day.getDay() >= 1 && day.getDay() <= 5) {
            return true;
        }
        else {
            return false;
        }
    }

    function getLastDate(date) {
        var month = date.getMonth() + 1;
        var year = date.getFullYear();
        var last;
        if (month == 2) {
            if (isLeapYear(year)) {
                last = date.setDate(29);
            }
            else {
                last = date.setDate(28);
            }

        }
        else if (month == 4 || month == 6 || month == 9 || month == 11) {
            last = date.setDate(30);

        }
        else {
            last = date.setDate(31);

        }
        return new Date(last);
    }

    function isLeapYear(year) {
        if (year % 100 == 0 && year % 400 == 0) {
            return true;
        }
        else if (year % 100 != 0 && year % 4 == 0) {
            return true;
        }
        else {
            return false;
        }
    }

    function preMark(memberId) {
        var date;
        if ($("#dpkr_month").val() != "") {
            var yr_mon = $("#dpkr_month").val().split('-');
            date = new Date(Date.parse(yr_mon[0] + "-01-" + yr_mon[1]));
            var d = 1;
            var last = getLastDate(date);
            do {
                date.setDate(d);
                if (isWeekday(date)) {
                    $("#" + memberId + "_d_" + date.getDate()).html("√");
                }
                d++;
            } while (last - date > 0);
        }
    }

    $(function () {
        $("#dpkr_month").datepicker({
            autoclose: true,
            todayHighlight: true,
            format: "yyyy-mm",

            minViewMode: "months",
            language: "zh-CN"
        });

        $("#btn_query").bind("click", function () {
            $("tr[id^='r_']").each(function () {

                preMark($(this).attr("id").split('_')[1]);
            });
            $.getJSON(
            location.protocol + "//" + location.host + location.pathname + "/Details/" + $("#dpkr_month").val(),
            function (data) {
                for (var i = 0; i < data.length; i++) {
                    var att_id = [];
                    if (data[i].TypeId <= 2) {
                        // on work
                        var start = new Date(Date.parse(data[i].Start)).getDate();
                        var finish = new Date(Date.parse(data[i].Finish)).getDate();
                        for (; start <= finish; start++) {
                            $("#" + data[i].MemberId + "_d_" + start).html(data[i].Symbol);
                        }
                    }
                    else {
                        // off work
                        var start = new Date(Date.parse(data[i].Start)).getDate();
                        var finish = new Date(Date.parse(data[i].Finish)).getDate();
                        for (; start <= finish; start++) {
                            $("#" + data[i].MemberId+"_d_"+start).html(data[i].Symbol);
                        }
                    }
                }
            });
        });

        $("#btn_export").bind("click", function () {

        });
    });
</script>

TaskAssignment/Areas/Admin/Views/Attendance/_TypeList.cshtml
@model IEnumerable<TaskAssignment.Persistence.AttendanceType>
@{
	Layout = null;
}
@{
	foreach (var item in Model)
	{
		<option value="@item.Id">@item.TypeName</option>
	}

}