TaskAssignment/Areas/Admin/Controllers/SubstationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskAssignment.Persistence;

namespace TaskAssignment.Areas.Admin.Controllers
{
    public class SubstationController : Controller
    {
        [ChildActionOnly]
        public ActionResult List() {
            var ctx = new TaskAssignmentModel();
            var list = ctx.Substations.DefaultIfEmpty();
            return View("_List", list);
        }

        public ActionResult All() {
            var ctx = new TaskAssignmentModel();
            var list = ctx.Substations.DefaultIfEmpty();
            return View(list);
        }
    }
}

TaskAssignment/Areas/Admin/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskAssignment.Areas.Admin.Models;
using TaskAssignment.Persistence;
using TaskAssignment.Util;

namespace TaskAssignment.Areas.Admin.Controllers
{
    public class TaskController : Controller
    {
        const int Type4Outdoor = 2;

        // GET: /Admin/Task/Show
        [HttpGet]
        public ActionResult Show() {

            return View();
        }

        [HttpPost]
        public ActionResult Show(DateRange model) {
            var ctx = new TaskAssignmentModel();
            var list = ctx.Tasks.Where(t => t.Date >= model.Start && t.Date <= model.Finish).OrderBy(t => t.Date);
            ViewBag.Start = model.Start.ToString("yyyy年MM月dd日");
            ViewBag.Finish = model.Finish.ToString("yyyy年MM月dd日");
            return View(list);
        }

        [HttpGet]
        public ActionResult Add() {

            return View();
        }

        [HttpPost]
        public ActionResult Add(AddTask model) {
            // Only invoke in Add.cshtml
            Task t = model.Task;
            var ctx = new TaskAssignmentModel();
            t.Visible = true;
            ctx.Tasks.Add(t);

            if (model.LeaderId > 0) {
                Assign leader = new Assign();
                leader.MemberId = model.LeaderId;
                leader.IsLeader = true;
                leader.TaskId = t.Id;
                ctx.Assigns.Add(leader);

                Attendance att = new Attendance();
                att.TaskId = t.Id;
                att.MemberId = model.LeaderId;
                att.StartDate = t.Date;
                att.FinishDate = t.Date;
                ctx.Attendances.Add(att);
            }

            foreach (var item in model.MemberId) {
                Assign asg = new Assign();
                asg.MemberId = item;
                asg.IsLeader = false;
                asg.TaskId = t.Id;

                Attendance att = new Attendance();
                att.TaskId = t.Id;
                att.MemberId = item;
                att.TypeId = Type4Outdoor; // The Type of outside work in DB is 2 (reffer to AttendanceType)
                att.StartDate = t.Date;
                att.FinishDate = t.Date;
                ctx.Assigns.Add(asg);
                ctx.Attendances.Add(att);
            }
            ctx.SaveChanges();

            ViewBag.Success = true;
            ViewBag.Message = "该工作已添加。";
            return View();
        }

        [HttpGet]
        public JsonResult Edit(int id) {
            var ctx = new TaskAssignmentModel();
            var task = ctx.Tasks.SingleOrDefault(t => t.Id == id);
            var result = new JsonResult();
            result.ContentEncoding = System.Text.Encoding.UTF8;
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;


            var tmp_list = task.Assigns.Where(t => t.TaskId == id && !t.IsLeader).ToList();
            long[] m_id = null;
            if (tmp_list != null && tmp_list.Count > 0) {
                m_id = new long[tmp_list.Count];
                for (int i = 0; i < m_id.Length; i++) {
                    m_id[i] = tmp_list[i].MemberId;
                }
            }

            var asg = task.Assigns.SingleOrDefault(t => t.TaskId == id && t.IsLeader);
            long l_id = 0;
            if (asg != null) {
                l_id = asg.MemberId;
            }
            result.Data = new {
                Id = task.Id,
                SubstationId = task.SubstationId,
                LocationId = task.Substation.LocationId,
                Content = task.Content,
                ConditionId = task.ConditionId,
                Date = task.Date.ToString("yyyy-MM-dd"),
                Visible = task.Visible,
                TypeId = task.TypeId,
                LeaderId = l_id,
                MemberId = m_id
            };
            return result;
        }

        [HttpPost]
        public ActionResult Edit(AddTask model) {
            if (model != null && model.Task != null && model.Task.Id > 0) {
                var ctx = new TaskAssignmentModel();
                var task = ctx.Tasks.SingleOrDefault(t => t.Id == model.Task.Id);
                ctx.Assigns.RemoveRange(task.Assigns);

                task.ConditionId = model.Task.ConditionId;
                task.Content = model.Task.Content;
                task.Date = model.Task.Date;
                task.SubstationId = model.Task.SubstationId;
                task.TypeId = model.Task.TypeId;

                //task.Visible = model.Task.Visible;
                // Notice: Attendance cascaded delete has been implement in DB by trigger


                if (model.LeaderId > 0) {
                    Assign leader = new Assign();
                    leader.MemberId = model.LeaderId;
                    leader.IsLeader = true;
                    leader.TaskId = task.Id;
                    ctx.Assigns.Add(leader);

                    Attendance att = new Attendance();
                    att.TaskId = model.Task.Id;
                    att.MemberId = model.LeaderId;
                    att.TypeId = Type4Outdoor; // The Type of outside work in DB is 2 (reffer to AttendanceType)
                    att.StartDate = task.Date;
                    att.FinishDate = task.Date;

                    ctx.Attendances.Add(att);
                }

                foreach (var item in model.MemberId) {
                    Assign asg = new Assign();
                    asg.MemberId = item;
                    asg.IsLeader = false;
                    asg.TaskId = task.Id;

                    Attendance att = new Attendance();
                    att.TaskId = model.Task.Id;
                    att.MemberId = item;
                    att.TypeId = Type4Outdoor; // The Type of outside work in DB is 2 (reffer to AttendanceType)
                    att.StartDate = task.Date;
                    att.FinishDate = task.Date;
                    ctx.Assigns.Add(asg);
                    ctx.Attendances.Add(att);
                }
                ctx.SaveChanges();
            }
            if (string.IsNullOrEmpty(model.ReturnAction)) {
                model.ReturnAction = "Add";
            }
            return RedirectToAction(model.ReturnAction);
        }

        public ActionResult Delete(int id, string rtnact) {
            var ctx = new TaskAssignmentModel();
            var task = ctx.Tasks.SingleOrDefault(t => t.Id == id);

            var asg = ctx.Assigns.Where(a => a.TaskId == id);
            if (asg != null && asg.Count() > 0) {
                ctx.Assigns.RemoveRange(asg);
            }

            // Notice: Attendance cascaded delete has been implement in DB by trigger

            if (task != null && task.Id != 0) {
                ctx.Tasks.Remove(task);
                ctx.SaveChanges();
                // Won't work currently
                //ViewBag.Success = true;
                //ViewBag.Message = "该工作已删除。";
            }
            if (rtnact == null || rtnact.Length == 0) {
                return RedirectToAction("Add");
            }
            else {
                return RedirectToAction(rtnact);
            }
        }

        public ActionResult Export(DateRange model) {
            var ctx = new TaskAssignmentModel();
            var tasks = ctx.Tasks.Where(t => t.Date >= model.Start && t.Date <= model.Finish).OrderBy(t => t.Date);
            string template = Server.MapPath("~/Content/templates/template-task.xlsx");
            string filename = "";
            if (model.Start == model.Finish) {
                filename = model.Start.ToString("MM.dd") + " 工作安排.xlsx";
            }
            else {
                filename = model.Start.ToString("MM.dd") + "-" + model.Finish.ToString("MM.dd") + " 工作安排.xlsx";
            }
            string exported = Server.MapPath("~/Content/exported/" + filename);
            try {
                ExcelHelper.Export(tasks, template, exported);
            }
            catch (Exception ex) {
                Global.Logger.AppendLog(ex);
            }

            if (System.IO.File.Exists(exported)) {
                FilePathResult result = new FilePathResult(exported, ExcelHelper.XlsxContentType);
                result.FileDownloadName = filename;
                return result;
            }
            else {
                return RedirectToAction("Error");
            }
        }

        [ChildActionOnly]
        public ActionResult Recent() {
            // Fetch the tasks that are already assigned this and the next  week 
            var ctx = new TaskAssignmentModel();
            const int fortnight = 14;
            DateTime thisWeekbegin = DateTime.Today.WeekBegin(DayOfWeek.Monday);
            DateTime nextWeekend = thisWeekbegin.AddDays(fortnight - 1);   // to next Sunday
            var tasks = ctx.Tasks
                .Where(t => t.Date >= thisWeekbegin && t.Date <= nextWeekend)
                .OrderBy(t => t.Assigns.Count);
            return View("_Recent", tasks);
        }

        [ChildActionOnly]
        public ActionResult AllTaskTypeList() {
            var ctx = new TaskAssignmentModel();
            var typeList=ctx.TaskTypes;

            return View();
        }

    }
}

TaskAssignment/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskAssignment.Persistence;

namespace TaskAssignment.Controllers
{
    public class MemberController : Controller
    {
        // GET: Member
        [ChildActionOnly]
        public ActionResult AllList()
        {
            var ctx = new TaskAssignmentModel();
            var model = ctx.Members.DefaultIfEmpty();
            return View("_AllList",model);
        }
    }
}

TaskAssignment/Areas/Admin/Views/Task/Add_Script.cshtml
<script>
    $(function () {
        $('.select2').select2();
        $('#tb_tasks').DataTable({
            "columnDefs": [
                { "width": "10%", "targets": 0 },
                { "width": "4%", "targets": 1 },
                { "width": "4%", "targets": 2 },
                { "width": "6%", "targets": 3 },
                { "width": "4%", "targets": 4 },
                { "width": "30%", "targets": 5 },
                { "width": "35%", "targets": 6 }
            ],
            'autoWidth': true,
            'lengthChange': false,
            'ordering': false,
            'info': false
        });

        //Date picker
        $('#datepicker').datepicker({
            autoclose: true,
            todayHighlight: true,
            language: 'zh-CN'
        });

        var delModal = $("#delModal");
        delModal.on("show.bs.modal", function (e) {
            // 这里的btn就是触发元素，即你点击的删除按钮
            var btn = $(e.relatedTarget),
                id = btn.attr("id").split('_')[2];
            $("#delModal button[type='submit']").bind("click", function () {
                location.href = location.protocol+"//"+location.host + "/Admin/Task/Delete/" + id;
            });
            // do your work
        })

        var editModal = $("#editModal");
        editModal.on("show.bs.modal", function (e) {
            // 这里的btn就是触发元素，即你点击的删除按钮
            var btn = $(e.relatedTarget),
                id = btn.attr("id").split('_')[2]; 
            // do your work
            $.getJSON(
                location.protocol + "//" + location.host + "/Admin/Task/Edit/" + id,
                function (data) {
                    $("#editModal input[name='Task.Id']").val(data.Id);
                    $("#editModal input[name='Task.Date']").val(data.Date);
                    $("#editModal select[name='Task.SubstationId'] option[value='" + data.SubstationId + "']")
                        .attr("selected", "selected");
                    $("#editModal select[name='Task.ConditionId'] option[value='" + data.ConditionId + "']")
                        .attr("selected", "selected");
                    $("#editModal select[name='Task.TypeId'] option[value='" + data.TypeId + "']")
                        .attr("selected", "selected");
                    $("#editModal textarea").html(data.Content);
                    $("#editModal select[name='LeaderId']").val(data.LeaderId);
                    $("#editModal select[name='LeaderId']").trigger("change");

                    $("#editModal select[name='MemberId']").val(data.MemberId);
                    $("#editModal select[name='MemberId']").trigger("change");
            });
        })


    });


</script>

TaskAssignment/Areas/Admin/Views/Task/DelModal.cshtml
<!-- Modal -->
<div class="modal modal-danger fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="取消"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">修改工作安排</h4>
            </div>
            <div class="modal-body">
                确认删除该工作吗？（该操作不可逆）
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="submit" class="btn btn-danger" onclick="">删除</button>
            </div>
        </div>
    </div>
</div>

TaskAssignment/Areas/Admin/Views/Task/EditModal.cshtml
<!-- Modal -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="取消"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">修改工作安排</h4>
            </div>
            @using (Html.BeginForm("Edit", "Task")) {
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>时间：</label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="Task.Id" style="display:none"/>
                                    <input type="text" name="ReturnAction" style="display:none"/>
                                    <input type="text" name="Task.Date" data-val="true" class="form-control pull-right" id="datepicker" />
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>站名：</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-industry"></i>
                                    </div>
                                    <select class="form-control select2" name="Task.SubstationId" style="width: 100%;">
                                        @Html.Action("List", "Substation")
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>工作条件：</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-wrench"></i>
                                    </div>
                                    <select class="form-control pull-right" name="Task.ConditionId">
                                        <option value="1">停电</option>
                                        <option value="2">不停电</option>
                                        <option value="3">其他</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>工作类型：</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-tag"></i>
                                    </div>
                                    <select class="form-control" name="Task.TypeId">
                                        <option value="1">预试</option>
                                        <option value="2">处缺</option>
                                        <option value="3">大修</option>
                                        <option value="4">其他</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>工作内容：</label>
                                <textarea name="Task.Content" class="form-control" rows="8" placeholder="输入工作内容 ..."></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>工作负责人：</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-user"></i>
                                    </div>
                                    <select name="LeaderId" class="form-control select2" style="width: 100%;">
                                        @Html.Action("AllList", "Member")
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>工作班成员：</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-users"></i>
                                    </div>
                                    <select name="MemberId" class="form-control select2" multiple="multiple" style="width: 100%;">
                                        @Html.Action("AllList", "Member")
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">保存</button>
                </div>
            }
        </div>
    </div>
</div>

TaskAssignment/Areas/Admin/Views/Task/Show.cshtml
@model IEnumerable<TaskAssignment.Persistence.Task>
@{
    ViewBag.Title = "查询工作计划";
    ViewBag.AppendixStyle = Styles.Render("~/plugins/css/addTasks");
    ViewBag.AppendixScripts = Scripts.Render("~/plugins/js/addTasks");
    ViewBag.PartialView = "Show_Script";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">工作安排查询</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    @using (Html.BeginForm()) {
                        <div class="form-group col-md-3">
                            <div class="input-group input-daterange">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input id="txt_start" name="Start" class="form-control" data-val="true" type="text" value="@ViewBag.Start" />
                                <div class="input-group-addon" style="border:none">至</div>
                                <input id="txt_finish" name="Finish" class="form-control" data-val="true" type="text" value="@ViewBag.Finish" />
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-success">查询</button>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="col-md-2 form-group pull-right">
                        <div class="input-group">
                            <button id="btn_export" class="btn btn-danger"><i class="fa fa-download"></i>&nbsp;&nbsp;导出 Excel</button>
                        </div>
                    </div>
                </div>

            </div>
            <table id="tb_tasks" class="table table-bordered table-hover" width="100%">
                <thead>
                    <tr>
                        <th>时间</th>
                        <th>分局</th>
                        <th>站名</th>
                        <th>电压等级</th>
                        <th>类型</th>
                        <th>工作内容</th>
                        <th>成员</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    @{ if (Model != null) {
                            foreach (var item in Model) {
                                <tr>
                                    <td>@item.Date.ToString("yyyy年MM月dd日")</td>
                                    <td>@item.Substation.Location.LocationName</td>
                                    <td>@item.Substation.SubstationName</td>
                                    <td>@item.Substation.Voltage kV</td>
                                    <td>@item.TaskType.TypeName</td>
                                    <td>@item.Content</td>
                                    <td>
                                        @{
                                            string names = "";
                                            var nameList = item.Assigns.Where(ta => ta.TaskId == item.Id).OrderByDescending(ta => ta.IsLeader);
                                            if (nameList != null && nameList.Count() > 0) {
                                                <b>@nameList.First().Member.Name，</b>
                                                foreach (var asg in nameList.Skip(1)) {
                                                    names += asg.Member.Name + "，";
                                                }
                                                names = names.Substring(0, names.Length - 1);
                                            }
                                        }
                                        @names
                                    </td>
                                    <td>
                                        <div class="tools">
                                            <button id="btn_edit_@item.Id" class="btn  btn-primary btn-xs" data-toggle="modal" data-target="#editModal">
                                                <i class="fa fa-edit"></i>&nbsp;编&nbsp;辑&nbsp;
                                            </button>
                                            <button id="btn_del_@item.Id" class="btn  btn-danger btn-xs pull-right" data-toggle="modal" data-target="#delModal">
                                                <i class="fa fa-trash-o"></i>&nbsp;删&nbsp;除&nbsp;
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                                }
                                            }
                    }
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>
@Html.Partial("EditModal")
@Html.Partial("DelModal")

TaskAssignment/Areas/Admin/Views/Task/Show_Script.cshtml
<script>
    $(function () {
        $('.select2').select2();
        $('#tb_tasks').DataTable({
            "columnDefs": [
                { "width": "9%", "targets": 0 },
                { "width": "4%", "targets": 1 },
                { "width": "4%", "targets": 2 },
                { "width": "6%", "targets": 3 },
                { "width": "4%", "targets": 4 },
                { "width": "30%", "targets": 5 },
                { "width": "30%", "targets": 6 }
            ],
            'autoWidth': true,
            'lengthChange': false,
            'ordering': false,
            'searching': false,
            'info': false
        });

        // Date picker initiate
        $('.input-daterange input').each(function () {
           
            $(this).datepicker({
                autoclose: true,
                todayHighlight: true,
                format: "yyyy-mm-dd",
                language: "zh-CN"
            });
        });

        // xlsx export
        $("#btn_export").bind("click", function () {
            // change the form action, then submit
            $("#btn_export").parent().parent().prev().attr("action", location.pathname.replace("Show","Export"));
            $("#btn_export").parent().parent().prev().submit();
            $("#btn_export").parent().parent().prev().attr("action", location.pathname);
        });

        var delModal = $("#delModal");
        delModal.on("show.bs.modal", function (e) {
            // 这里的btn就是触发元素，即你点击的删除按钮
            var btn = $(e.relatedTarget),
                id = btn.attr("id").split('_')[2];
            $("#delModal button[type='submit']").bind("click", function () {
                location.href = location.protocol + "//" + location.host + "/Admin/Task/Delete/" + id+"?rtnact=Show";
            });
            // do your work
        })

        var editModal = $("#editModal");
        editModal.on("show.bs.modal", function (e) {
            // 这里的btn就是触发元素，即你点击的删除按钮
            var btn = $(e.relatedTarget),
                id = btn.attr("id").split('_')[2];
            // do your work
            $.getJSON(
                location.protocol + "//" + location.host + "/Admin/Task/Edit/" + id,
                function (data) {
                    $("#editModal input[name='Task.Id']").val(data.Id);
                    $("#editModal input[name='ReturnAction']").val("Show");
                    $("#editModal input[name='Task.Date']").val(data.Date);
                    $("#editModal select[name='Task.SubstationId'] option[value='" + data.SubstationId + "']")
                        .attr("selected", "selected");
                    $("#editModal select[name='Task.ConditionId'] option[value='" + data.ConditionId + "']")
                        .attr("selected", "selected");
                    $("#editModal select[name='Task.TypeId'] option[value='" + data.TypeId + "']")
                        .attr("selected", "selected");
                    $("#editModal textarea").html(data.Content);
                    $("#editModal select[name='LeaderId']").val(data.LeaderId);
                    $("#editModal select[name='LeaderId']").trigger("change");

                    $("#editModal select[name='MemberId']").val(data.MemberId);
                    $("#editModal select[name='MemberId']").trigger("change");
                });
        });


    });


</script>